name: Dev Manual Deployment

on:
  workflow_dispatch:
    # inputs:
    #   update-platform:
    #     required: false
    #     type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: ssh key passphrase
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        passphrase: ${{ secrets.PASSPHRASE }}
        # fingerprint: ${{ secrets.FINGERPRINT }}
        script: |
          whoami
          ls -al
        #   set -e
        #   cd ${{ secrets.WORK_DIR }}
        #   git status
        #   git stash
        #   git checkout develop
        #   git pull
        #   git stash pop || true
        
        #   docker compose down

        # if: ${{ !inputs.skip-tests }}
        # run: |
        #   ./scripts/install_submodules.sh update-platform
        
        # if: ${{ !inputs.skip-tests }}
        # run: |
        #   ./scripts/install_submodules.sh update-platform-submodules


        #   docker compose run --rm problem-solver build /kb/repo.path
        #   docker compose up -d
        #   docker compose ps
        #   docker compose logs --tail=100 
        #   exit
         
       