name: Manual Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Update repository and deploy containers
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: | 
          set -e
          cd ${{ secrets.WORK_DIR }}/interface/health-care-ui/
          git status

          cd ${{ secrets.WORK_DIR }}
          docker compose ps
          docker compose logs --tail=100 ui
          exit
    
