
name: dev

on:
  push:
    branches: [main]
  workflow_dispatch:
env:
  python-vars: ${{ vars.WITHOUT_PYTHON_AGENTS_TESTS }}

jobs:
  check-dev:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' }} 
    uses: ./.github/workflows/template_workflow.yml
    secrets:
      sftp-user: ${{ secrets.SFTP_USER }}
      sftp-pass: ${{ secrets.SFTP_PASS }}
      sftp-host: ${{ secrets.SFTP_HOST }}
      sftp-port: ${{ secrets.SFTP_PORT }}
        
  build-kb-dev:
    name: build-kb-dev - ${{ matrix.os }}
    needs: check-dev
    if: ${{ needs.check-dev.outputs.others-var == 'true' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    env:
      TERM: linux

    steps:
      - name: Download artifact from previous job
        uses: actions/download-artifact@v4
        with:
          name: build-output - ${{ matrix.os }}
      
      - name: Display structure of downloaded artifact
        run: ls -R  
      

