name: sc-machine

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sc-machine:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    env:
      TERM: linux
    steps:
      - name: checkout
        uses: actions/checkout@v3 # Necessary to access local action
        with:
          submodules: recursive
          
      - name: Local Action Call
        uses: ./subsystems/sc-machine/.github/workflows/sanitizers.yml
    