name: Calling Reusable Workflows
on:
  push:
  workflow_dispatch:
    inputs:
      name:
        description: "Input description"
        type: string
        default: "Ali"
        required: false
jobs:
  calling-a-reusable-wf:
    uses: kuanysh-zhk/reusable_workflow/.github/workflows/sanitizer.yml@main