name: prod
run-name: Prod - ${{ github.ref_name }} - ${{ github.sha }} -by ${{ github.actor }}  

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      skip-tests:
        required: true
        type: boolean

jobs:
  check-prod:
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/template_workflow.yml
    secrets:
      sftp-user: ${{ secrets.SFTP_USER }}
      sftp-pass: ${{ secrets.SFTP_PASS }}
      sftp-host: ${{ secrets.SFTP_HOST }}
      sftp-port: ${{ secrets.SFTP_PORT }}
    with:
      skip-tests: ${{ github.event.inputs.skip-tests == 'true' }}
  
  build-kb-prod:
    name: build-kb-prod - ${{ matrix.os }}
    needs: check-prod
    if: ${{ needs.check-prod.outputs.others-var == 'true' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    env:
      TERM: linux

    steps:
      - name: Checkout action
        uses: actions/checkout@v4
      
      - name: Download artifact from previous job
        uses: actions/download-artifact@v4
        with:
          name: build-output - ${{ matrix.os }}
      
      - name: Display structure of downloaded artifact
        run: ls -R  

      - name: Configure extension part of knowledge base
        run: |
          ./scripts/configure_kb_extension.sh

      - name: Build knowledge base -PROD
        run: |
          sudo chmod -R +x .
          sudo ./scripts/build_kb.sh -prod
