name: template_workflow

on:
  # It's callable template
  workflow_call:
    secrets:
      sftp-user:
        required: true
      sftp-pass:
        required: true
      sftp-host:
        required: true
      sftp-port:
        required: true
    inputs:
      skip-tests:
        required: false
        type: boolean
    outputs:
      others-var:
        description: "Other steps"
        value: ${{ jobs.others.outputs.output2 }}

jobs:
  check-changes:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    env:
      TERM: linux
    # Set job outputs to values from filter step
    outputs:
      python: ${{ steps.filter.outputs.python }}
      others: ${{ steps.filter.outputs.others }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
        
    - name: Checking changes
      uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          python:
            - '**'
          others:
            - '!problem-solver/py_kpm_based/**'

  # JOB to build only python dependecies and tests
  python:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.python == 'true' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    env:
      TERM: linux
    steps:
      - name: Checkout
        uses: actions/checkout@v4
                
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Cache pip packages
        id: cache-pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Checking existence of pip cache
        run: echo "Cache exists ${{ steps.cache-pip.outputs.cache-hit }}"
        
      - name: Install Python dependencies
        run: |
          ./scripts/install_python_deps.sh
          
  # JOB to build others steps
  others:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.others == 'true' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    env:
      TERM: linux
    outputs:  
      output2: ${{ steps.others-step.outputs.others-var }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Update
        run: |
          sudo apt-get update

      - name: Create build-utput artifact
        uses: actions/upload-artifact@v4
        with:
            name: build-output - ${{ matrix.os }}
            path: .

      - name: Verify variables to move further
        id: others-step
        run: | 
          echo "others-var=true" >> $GITHUB_OUTPUT
